#!/bin/bash

# config -- no need to modify the entire script if you use a torrent client other than deluge :)
DEBUG=0                   # excessive logging output to log file and terminal screen (when triggered direct) - use wisely!!
IFCONFIG=/sbin/ifconfig   # whereis ifconfig
INTERFACE=tun0            # ip a
CLIENT=deluge-gtk         # ps aux | grep [name of torrent client]
CLI=0                     # leave 0 if you are using the desktop launcher method
DIR=$(dirname "$0")
LOGPATH="$DIR"/"$CLIENT"-kill.log

# if the client is running already, a torrent dl might be being passed as an argument (%U), so feed it to the client and die
if [ ! "$(pgrep -a $CLIENT)" == "" ] && [ $CLI == 0 ];
then

  "$CLIENT" "$1"
  exit 0
fi

function logMessage() {

  # always log to vpn-check directory
  echo "$(date) $1" >> "$LOGPATH"
}


function extinct() {

  logMessage "${INTERFACE} interface or ${CLIENT} process is down, terminating ${CLIENT} to be safe..."

  if [ $CLI == 1 ];
  then
    echo -e "\e[31m${INTERFACE} interface or ${CLIENT} missing, performing a kill signal...\e[0m"
  else

    # throw a notification on desktop that the vpn signal was lost
    if [ -f /usr/bin/notify-send ];
    then
      notify-send -i error "VPN Connection Lost, Killswitch Activated" \
      -u critical \
      "See $LOGPATH\
      \rfor details."
    fi
  fi

  # forcefully terminate, otherwise if we wait for it to gracefully close, there's risk of exposure outside of the vpn
  pkill -f $CLIENT -9
  # for good measure, clean exit
  exit 0
}


function vpnCheck() {
  if [ "$DEBUG" == "1" ];
  then
    logMessage "vpnCheck function triggered"
  fi

  # trigger an infinite loop, until the client is closed or tunnel is dropped
  while true;
    do
      sleep 1

      if [ ! "$($IFCONFIG | grep $INTERFACE)" == "" ] && [ ! "$(pgrep -a $CLIENT)" == "" ]; then

        # everything is working, do nothing
        if [ "$DEBUG" == "1" ];
        then
          logMessage "${CLIENT} and ${INTERFACE} are active"
        fi
      else

        # no tunnel or client process detected; terminating
        extinct
      fi
    done
}

### startup
if [ "$DEBUG" == "1" ];
then
  logMessage "VPN Killswitch has been initiated"
fi

if [ $CLI == 0 ];
then
  # launch the torrent client as it's own parent process
  nohup "$CLIENT" &
else
  # give the torrent client a moment to boot before we start thumping out processes
  echo -e "\e[32m>> VPN Killswitch has been initiated! <<\e[0m  \nIf $CLIENT isn't boot immediately after the killswitch is launched, it will be terminated; so start services accordingly!"
  sleep 5
fi

vpnCheck
